openeye/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import home, home_files
from openeye import views
from catalogue import views as catalogue_views


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', home, name='home'),
    url(r'^main/$', views.MainView.as_view(), name='MainView'),
    url(r'^topic/(?P<pk>[0-9]+)/$', catalogue_views.TopicView.as_view(), name='TopicView'),
    url(r'^resource/(?P<pk>[0-9]+)/$', catalogue_views.DetailView.as_view(), name='ResourceDetail'),
    url(r'^contribute/$', catalogue_views.ContributeView.as_view(), name='Contribute'),
    url(r'^(?P<filename>(robots.txt)|(humans.txt))$', home_files, name='home-files'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
]

catalogue/models.py
from django.db import models
from django.contrib.auth.models import User


# Extending the default Django user model with Profile to allow addition of extra fields
class Profile(models.Model):
    user = models.OneToOneField(User)
    role = models.CharField(max_length=2000, blank=True)
    pledge = models.CharField(max_length=2000, blank=True)
    is_curator = models.BooleanField(default=False)


class TopicArea(models.Model):
    name = models.CharField(max_length=40)
    # TODO check database max lengths for text fields
    definition = models.CharField(max_length=2000, blank=True)
    curator = models.ForeignKey(User)
    active = models.BooleanField(default=True)
    visible = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
    date_modified = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.name

    # Method to show the curator, if there is one
    def curator_name(self):
        if self.curator.get_full_name() == "":
            return ""
        else:
            return "(" + self.curator.get_full_name() + ")"

    # TODO Add method to calculate days since resource added


class Level(models.Model):
    level_desc = models.CharField(max_length=10)
    active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
    date_modified = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.level_desc


class JobType(models.Model):
    job = models.CharField(max_length=40)
    active = models.BooleanField(default=True)
    date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
    date_modified = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.job


class CatalogueItem(models.Model):
    title = models.CharField(max_length=80)
    # TODO check database max lengths for text fields
    description = models.TextField(max_length=2000, blank=True)
    topic_area = models.ForeignKey(TopicArea)
    level = models.ForeignKey(Level)
    link = models.CharField(max_length=255)
    discovered_by = models.ForeignKey(User)
    what_learn = models.TextField(max_length=2000, blank=True)
    how_apply = models.TextField(max_length=2000, blank=True)
    relevant_to = models.ManyToManyField(JobType)
    date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
    date_modified = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return self.title

    def full_name(self):
        # Fetches full name of the discovered_by linked user
        return self.discovered_by.get_full_name()

catalogue/forms.py
from django import forms
from .models import CatalogueItem, JobType


class ContributeForm(forms.ModelForm):

    class Meta:
        model = CatalogueItem
        fields = ['title', 'topic_area', 'description', 'link', 'what_learn', 'how_apply', 'level', 'relevant_to', 'discovered_by']


    # Fetch all the values in JobTypes to label the check boxes in the form
    ROLE_CHOICES = [[x.id, x.job] for x in JobType.objects.all().order_by('job')]

    title = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'To sell this resource to others'}), max_length=80, required=True)
    description = forms.CharField(widget=forms.Textarea(attrs={'rows': 2, 'placeholder': 'Clear, e.g. format, duration, activities...'}))
    link = forms.CharField(widget=forms.URLInput(attrs={'placeholder': 'If required, link to resource http://...'}), required=False)
    what_learn = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'placeholder':"This is important, it's the reason for adding this learning resource, so please be specific."}), label='What will you learn?')
    how_apply = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'placeholder':"How could this be put into action afterwards?"}), label='How could you apply this?')
    relevant_to = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, choices=ROLE_CHOICES)

catalogue/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from .models import TopicArea, CatalogueItem
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from .forms import ContributeForm
# Create your views here.


# the MAIN PAGE for REGISTERED USERS
class TopicView(generic.ListView):

    template_name = "openeye/topic.html"
    context_object_name = 'resource_list'
    paginate_by = 5

    # TODO Make this only active topic areas?
    def get_queryset(self, *args, **kwargs):
        return CatalogueItem.objects.filter(topic_area_id=self.kwargs['pk'])

    def get_context_data(self, **kwargs):
        context = super(TopicView, self).get_context_data(**kwargs)
        # context['TopicName'] = TopicArea.objects.filter(id=self.kwargs['pk'])
        context['TopicName'] = TopicArea.objects.get(id=self.kwargs['pk'])
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(TopicView, self).dispatch(*args, **kwargs)


class DetailView(generic.DetailView):

    template_name = "openeye/resource_detail.html"
    model = CatalogueItem
    context_object_name = 'resource'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DetailView, self).dispatch(*args, **kwargs)


class ContributeView(generic.CreateView):

    template_name = "openeye/contribute.html"
    form_class = ContributeForm
    success_url = reverse_lazy('MainView')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ContributeView, self).dispatch(*args, **kwargs)

openeye/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from catalogue.models import TopicArea


def home(request):
    return render(request, "openeye/index.html", {})


# Render robots.txt and humans.txt if requested
def home_files(request, filename):
    return render(request, filename, {}, content_type="text/plain")


# the MAIN PAGE for REGISTERED USERS
class MainView(generic.ListView):

    template_name = "openeye/main.html"
    context_object_name = 'topic_list'

    # TODO Make this only active topic areas?
    def get_queryset(self):
        return TopicArea.objects.all().order_by('name')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MainView, self).dispatch(*args, **kwargs)

openeye/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block head_title %}{% endblock %}</title>
        <link rel="shortcut icon" href="{% static 'favicon2.ico' %}" type="image/x-icon">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
        </style>
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">

        <script src="{% static 'js/vendor/modernizr-2.6.2-respond-1.1.0.min.js' %}"></script>
        {% block head_css %}{% endblock %}
        {% block head_javascript %}{% endblock %}
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->


        {% block navbar %}
            {% if user.is_authenticated %}

            <nav class="navbar navbar-inverse navbar-fixed-top role="navigation">
              <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="{% url 'MainView' %}">OpenEye</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav">
                    <li><a href="#">My Contributions <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">My Learning</a></li>
                  </ul>
                  <form class="navbar-form navbar-left" role="search">
                    <div class="form-group">
                      <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                  </form>
                  <ul class="nav navbar-nav navbar-right">
                    {% if request.user.profile.is_curator %}
                      <li><a href="#">Curators</a></li>
                    {% endif %}
                    {% if request.user.is_staff %}
                        <li><a href="/admin/">Admin</a></li>
                    {% endif %}
                     <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username.upper }}<span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><a href="#">Profile</a></li>
                        <li><a href="#">Preferences</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'logout' %}?next=/">Logout</a></li>
                      </ul>
                    </li>
                  </ul>
                </div><!-- /.navbar-collapse -->
              </div><!-- /.container -->
            </nav>

        {% else %}
             <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <p class="navbar-text">OpenEye - Not logged In</p>
                    </div>
                    <ul class="nav navbar-text navbar-right">
                        <!-- TODO Remove this -->
                        <li class="active"><p>{{ user.username.upper }}</p></li>
                    </ul>
                </div>
        {% endif %}
        {% endblock %}

    {% block content %}{% endblock %}

    <hr>
    
    <div class="container">  
      <footer>
        <p>&copy; OpenEye 2015</p>
      </footer>
    </div> <!-- /container -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="static/js/vendor/jquery-1.11.0.min.js"><\/script>')</script>

        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>

        <script src="{% static 'js/main.js' %}"></script>

        {% block footer_javascript %}{% endblock %}

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');
        </script>
    
       {% block extra_scripts %}
           
       {% endblock extra_scripts %}
    </body>
</html>

openeye/templates/navbar.html
{% block navbar_guest %}
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">OpenEye</a>
      </div>
        <div class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-primary">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </div>
{% endblock navbar_guest %}

openeye/templates/openeye/contribute.html
{% extends "base.html" %}


{% load staticfiles %}
{% load bootstrap3 %}


{% block head_title %}OpenEye | Login {% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="container">
            <div class="hero row">
                <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
                    <p>Thank you for suggesting a learning resource.  Please pay special attention to the "what you will learn" and "how to apply" information..</p>
                </div>
            </div>
        </div>
    </div>

        <div class="container">
            <div class="entry-form row">
                <div class="col-md-10 col-md-offset-1 col-sm-10 col-sm-offset-1 col-xs-10 col-xs-offset-1">
                    <form action="" method="post" class="form">
                        <input type="hidden" name="next" value="{{ next }}">
                        {% bootstrap_form form %}
                        <button class="btn btn-primary btn-lg" type="submit">Submit Suggestion</button>
                        {% csrf_token %}
                    </form>
            </div>
        </div>
    </div>

{% endblock content %}

{% block extra_scripts %}
    <script type="text/javascript">
        $(function () {
            // When the page has finished loading,
            // autofocus on the username field
            $('input#id_title').focus();
        });
    </script>
{% endblock %}

openeye/templates/openeye/index.html
{% extends "base.html" %}

<!-- Need to add the line below even though inherited because I'm using static refs -->
{% load staticfiles %}

{% block head_title %}OpenEye | Curated Catalogue{% endblock %}


{% block content %}
    <!-- Main area for message or call to action -->
    <div class="jumbotron">
        <div class="container">
            <div class="hero row">
                <div class="col-md-6 col-md-offset-3">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" data-interval="3000">
                        <!-- Indicators, I removed these and we are using no carousel-caption -->

                        <!-- Wrapper for slides -->
                        {# TODO Get all images the same size for carousel #}
                        <div class="carousel-inner">
                            <div class="item active">
                                <img src="{% static 'media/openeye-banner.jpg' %}" alt="...">
                            </div>
                            <div class="item">
                                <img src="{% static 'media/openeye2-banner.jpg' %}" alt="...">
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" role="button"
                           data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" role="button"
                           data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>
                    <!-- Carousel -->
                    <p>&nbsp;</p>
                    <p>Welcome to the OpenEye catalogue.</p>
                    <p>To use this site you need to be a registered user.</p>
                    <p><a class="btn btn-primary btn-lg" href="{% url 'login' %}?next=/main" role="button">Continue...</a>
                </div>
            </div>
        </div>
        <!-- end hero -->


    </div>


{#    </div>#}


{% endblock %}

openeye/templates/openeye/lpanel.html
            <div class="lpanel">
                <div class="col-md-2 col-sm-2">
                    <h4>Options</h4>
                    <a href="{% url 'MainView' %}">Main Contents</a>
                    <p></p>
                    <a href="{% url 'Contribute' %}">Suggest a resource</a>
                    <p>Search by role/activity</p>
                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}?next=/">Logout</a>
                    {% else %}
                        <<a href="{% url 'login' %}?next=/">Login</a>
                    {% endif %}
                </div>
            </div>

openeye/templates/openeye/main.html
{% extends "base.html" %}

<!-- Need to add the line below even though inherited because I'm using static refs -->
{% load staticfiles %}

{% block head_title %}OpenEye | Curated Catalogue{% endblock %}

{% block content %}
    <!-- Main area for message or call to action -->
    <div class="jumbotron" xmlns="http://www.w3.org/1999/html">
        <div class="container">
            <div class="hero row">
                <div class="col-md-6 col-md-offset-3">
                    <p>Curated Resources</p>
                </div>
            </div>
        </div>
        <!-- end hero -->
    </div>

    <div class="container">
        <div class="row">
            {% include 'openeye/lpanel.html' %}

            <div class="cpanel">
                <div class="col-md-6 col-sm-6">
                    <h4>Curated Content Categories</h4>
                    {% if topic_list %}
                        <dl>
                            {% for topic in topic_list %}
                                <p></p><a href="{% url 'TopicView' pk=topic.id %}">{{ topic.name }}</a>&nbsp;<span class="name">{{ topic.curator_name }}</span></p>
                            {% endfor %}
                        </dl>
                    {% endif %}
                </div>
            </div>
            <div class="rpanel">
                <div class="col-md-4 col-sm-4">
                    <h4>Activity Dashboard</h4>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

openeye/templates/openeye/resource_detail.html
{% extends "base.html" %}

<!-- Need to add the line below even though inherited because I'm using static refs -->
{% load staticfiles %}

{% block head_title %}OpenEye | Curated Catalogue{% endblock %}

{% block content %}
    <!-- Main area for message or call to action -->
    <div class="jumbotron" xmlns="http://www.w3.org/1999/html">
        <div class="container">
            <div class="hero row">
                <div class="col-md-6 col-md-offset-3">
                    <p>{{ resource.title }}</p>
                </div>
            </div>
        </div>
        <!-- end hero -->
    </div>

    <div class="container">
        <div class="row">
            {% include 'openeye/lpanel.html' %}

            <div class="cpanel">
                <div class="col-md-8 col-sm-8">
                    <h4>Details of this Upskilling Resource</h4>
                    {% if resource %}
                        <dl>
                            <p class="res_title">{{ resource.description }}</p>
                            <p class="res_title">Discovered by&nbsp;{{ resource.full_name }}&nbsp;and curated by</p>
                            <p class="res_desc">Added to Catalogue:&nbsp;{{ resource.date_created }}</p>
                            <p></p>
                            <p class="res_title">YOU WILL LEARN</p>
                            <p class="res_desc">{{ resource.what_learn }}</p>
                            <p class="res_title">TO APPLY THIS</p>
                            <p class="res_desc">{{ resource.how_apply }}</p>
                        </dl>
                    {% else %}
                        <p>Odd, there is no record to show?</p>
                    {% endif %}



                </div>
            </div>
        </div>
    </div>

{% endblock %}

openeye/templates/openeye/topic.html
{% extends "base.html" %}

<!-- Need to add the line below even though inherited because I'm using static refs -->
{% load staticfiles %}

{% block head_title %}OpenEye | Curated Catalogue{% endblock %}

{% block content %}
    <!-- Main area for message or call to action -->
    <div class="jumbotron" xmlns="http://www.w3.org/1999/html">
        <div class="container">
            <div class="hero row">
                <div class="col-md-6 col-md-offset-3">
                    <p>{{ TopicName }}</p>
                </div>
            </div>
        </div>
        <!-- end hero -->
    </div>

    <div class="container">
        <div class="row">

            {% include 'openeye/lpanel.html' %}


            <div class="cpanel">
                <div class="col-md-8 col-sm-8">
                    <h4>Resources</h4>
                    {% if resource_list %}
                        <dl>
                            {% for item in resource_list %}
                                <p class="res_title"><a href="{% url 'ResourceDetail' item.id %}">{{ item.title }}</a>&nbsp;<span class="name">(Discovered by&nbsp;{{ item.full_name }})</span></p>
                                <p class="res_desc">{{ item.description }}</p>
                                <p class="res_desc">YOU WILL LEARN:&nbsp;{{ item.what_learn }}</p>
                            {% endfor %}
                    </dl>
                    {% else %}
                        <p>Sorry, there is no content for this topic yet.</p>
                    {% endif %}

                    {% if is_paginated %}
                        <div class="pagination">
                            <span class="page-links">
                                {% if page_obj.has_previous %}
                                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                                {% endif %}
                                <span class="page-current">
                                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                                </span>
                                {% if page_obj.has_next %}
                                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                                {% endif %}
                            </span>
                        </div>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}